---
- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    osx_script: ./files/osx.sh

    mas_installed_apps:
      - { id: 405843582, name: "Alfred" }
      - { id: 441258766, name: "Magnet" }
      - { id: 1444383602, name: "GoodNotes 5" }
      - { id: 1534275760, name: "Languagetool" }

    homebrew_installed_packages:
      # - alacritty
      - argo
      - argocd
      - awscli
      - bat # cat with wings
      - cmake
      - coreutils # GNU File, Shell, and Text utilities
      - datawire/blackbird/telepresence-legacy
      - direnv # env managing
      - dog # command line DNS client
      - dua-cli # View disk space usage and delete unwanted data, fast
      - duf # Disk Usage/Free Utility
      - entr # Run arbitrary commands when files change
      - exa # Modern replacement for 'ls'
      - fd # Simple, fast and user-friendly alternative to find
      - findutils # Collection of GNU find, xargs, and locate
      - fluxcd/tap/flux # a set of continuous and progressive delivery solutions for Kubernetes that are open and extensible
      - fluxctl
      - fzf
      - gh # GitHub command-line
      - git-delta # A syntax-highlighting pager for git, diff, and grep output
      - git-filter-repo # Quickly rewrite git repository history
      - gitui # terminal-ui for git written in rust
      - glow # Render markdown on the CLI
      - gnu-tar
      - go
      - golangci-lint
      - gomodifytags
      - gopass
      - goreleaser
      - gron # Make JSON greppable!
      - hadolint # Dockerfile linter, validate inline bash
      - hashicorp/tap/terraform-ls
      - helm
      - hledger
      - htop
      - httpie
      - hugo
      - hurl
      - imagemagick
      - infracost # Cloud cost estimation for terraform
      - ipython
      - isync
      - jenv
      - jq
      - jupyterlab
      - k6 # Load testing tool
      - k9s # terminal based UI to interact with your Kubernetes clusters
      - khal # cli calendar
      - kind
      - koekeishiya/formulae/skhd # Hotkey Daemon MacOS
      - koekeishiya/formulae/yabai # Tiling Window Manager
      - kube-linter
      - kubeconform # Kubernetes manifest validation tool
      - kubectx
      - kubeseal # Store kube secret in git
      - kubeval # Kubenetes validation
      - kustomize # Kubernetes native configuration management
      - kyverno # policy engine for Kubernetes
      - latexindent
      - lazydocker # terminal UI for both docker and docker-compose
      - lazygit
      - lf
      - lua-language-server
      - luarocks # lua package manager
      - mdbook # command line tool to create books with Markdown
      - mitmproxy # interactive HTTPS proxy
      - moreutils # Collection of tools that nobody wrote when UNIX was young
      - msmtp
      - mysql-client
      - neomutt # command line mail reader
      - neovim
      - neovim-remote
      - newsboat # RSS feed reader
      - nmap
      - nnn # Terminal file manager
      - notmuch # Thread-based email index, search, and tagging
      - notmuch-mutt
      - npm
      - n # node version manager
      - xwmx/taps/nb # note taking app
      - openjdk@11
      - openjdk@17
      - pandoc # Universal markup converter
      - pdfgrep # Grep in PDF
      - prettier
      - pulumi # Terraform alt
      - pwgen # Password gen
      - rcm # *rc file manager
      - ripgrep
      - shellcheck # shell script analysis tool
      - sketchybar
      - slides # Terminal based presentation tool
      - stern # Tail multiple Kubernetes pods & their containers
      - stylua # lua code formatter
      - tectonic # latex engine
      - terraform-docs
      - texlab
      - tflint
      - tig
      - tmux
      - tokei # Count code
      - trash-cli
      - tree
      - urlview
      - vale
      - vdirsyncer
      - viddy # modern watch command
      - vifm # file manager with curses interface
      - w3m # Pager/text based browser
      - wget
      - xclip
      - yq
      - zoxide # smart cd command
      - hashicorp/tap/consul

    homebrew_uninstalled_packages: []

    homebrew_taps:
      - FelixKratz/formulae
      - homebrew/cask-fonts

    homebrew_cask_apps:
      # - alt-tab # Alt tab like window
      - bartender # Menu bar icon organizer
      # - betterdisplay # more display options
      # - docker
      - firefox
      - font-hack-nerd-font
      - google-cloud-sdk
      # - google-chrome
      - handbrake # Open-source video transcoder
      - karabiner-elements # keyboard customizer
      - keycastr # keystroke visualizer
      - kitty
      - keepassxc # Password manager app
      - libreoffice
      - macfuse # dependecy of telepresence
      # - middle # Add middle click to Mac
      # - min # minimal browser with no distractions
      # - mouse-fix # fix scrolling for external mice
      # - numi # Calculator and converter application
      # - postman
      - stats # System monitor for the menu bar
      - syncthing # Sync data between devices
      - skim # pdf viewer for vim-latex
      - shottr # screencapture tool
      - boop # scriptable scratchpad for developers
      # - forklift # finder alternative
      - linearmouse # mouse util
      - 1password/tap/1password-cli

    homebrew_cask_uninstalled_apps: []

    # vars for ansible-role-pip
    pip_packages:
      # - "molecule[docker]"
      # - molecule pynacl build fails
      - pytest-testinfra
      - selenium

    # vars for ansible-role-binaries
    # these are apps that are either not available with brew
    # or I require a fixed version
    kubectl_version: 1.22.0
    pet_version: 0.4.0
    tfswitch_version: 0.13.1300
    goMarkableClient_version: 0.6.4
    binaries:
      - name: kubectl
        url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/darwin/arm64/kubectl"
      - name: pet # Simple command-line snippet manager
        url: "https://github.com/knqyf263/pet/releases/download/v{{ pet_version }}/pet_{{ pet_version }}_darwin_arm64.tar.gz"
        extract: true
      - name: tfswitch
        url: "https://github.com/warrensbox/terraform-switcher/releases/download/{{tfswitch_version}}/terraform-switcher_{{tfswitch_version}}_darwin_arm64.tar.gz"
        extract: true
      - name: gh-md-toc # Generate TOC for README.md
        url: "https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc"
        extract: false

  tasks:
    - import_tasks: tasks/osx.yml

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - ansible-role-dotfiles
    - ansible-role-pip
    - ansible-role-binaries
