---
roles:
  - name: ansible-role-dotfiles
    src: https://github.com/kwanpham2195/ansible-role-dotfiles.git
    scm: git
    version: master
  - name: ansible-role-pip
    src: https://github.com/kwanpham2195/ansible-role-pip.git
    scm: git
    version: main
  - name: ansible-role-binaries
    src: https://github.com/kwanpham2195/ansible-role-binaries.git
    scm: git
    version: master

collections:
  - name: geerlingguy.mac
